### ISSUE TITLE
test-retry was unable to retry tests when BeforeAllCallback failed

### ISSUE THREAD

**Issue by iluxa-com** [gradle/test-retry-gradle-plugin#72] opened 2020-09-03 13:29 UTC
We use BeforeAllCallback from junit-jupiter via ExtendWith annotation on the test classes to setup the tests.
Sometimes the setup fails, unfortunately. In this case, re-try plugin fails to retry the whole test class tests with the error:
```
 java.lang.IllegalStateException: org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
   com.test.Test#initializationError
```

**Comment by ldaley** [comment] 2020-11-13 03:37
Suspected duplicate of #40. If it is still occurring with the latest version, please reopen with a reproducing example.

**Closed by ldaley** 2020-11-13 03:37 UTC
