### ISSUE TITLE
Unable to retry for the test name that contains [round, square] brackets

### ISSUE THREAD

**Issue by joey-yoonsung** [gradle/test-retry-gradle-plugin#155] opened 2022-11-04 06:57 UTC
``` 
org.gradle.test-retry was unable to retry the following test methods, which is unexpected.
```
Retrying is not working with the above error message.
I found the cause is the test name contains round brackets `()` or square brackets`[]`
 * I mean when the name contains any character of round and square brackets. - `(`, `)`, `[`, `]`.
 * I use Kotlin, defining the test name with backticks as the method name.
```kotlin
   @Test
   fun `my test()`() {

   }
```

**Comment by KroArtem** [comment] 2022-11-10 21:36
I think it's a duplicate of https://github.com/gradle/test-retry-gradle-plugin/issues/123

**Comment by marcphilipp** [comment] 2022-11-11 14:21
Duplicate of #123

**Closed by marcphilipp** 2022-11-11 14:21 UTC
