### ISSUE TITLE
Retry fails with an error

### ISSUE THREAD

**Issue by starflutesg** [gradle/test-retry-gradle-plugin#37] opened 2020-02-20 17:54 UTC
retry attempt fails with the below error and it never retried executing failed test.. gradle 4.10.2

error message on console 

> org.gradle.test-retry was unable to retry the following test methods. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues

**Comment by breskeby** [comment] 2020-02-21 21:56
@starflutesg thanks for reporting. is there a chance you can share a reproducible example of that failure?

**Comment by ldaley** [comment] 2020-04-15 21:36
Closing due to lack of information.

**Closed by ldaley** 2020-04-15 21:36 UTC
