### ISSUE TITLE
Unable to retry test methods from parent classes with Spock 2

### ISSUE THREAD

**Issue by rieske** [gradle/test-retry-gradle-plugin#91] opened 2021-01-25 08:37 UTC
Minimal reproducer:

`build.gradle`:
```
plugins {
    id("groovy")
    id("org.gradle.test-retry") version("1.2.0")
}

test {
    useJUnitPlatform()
    retry {
        maxRetries = 1
    }
}

dependencies {
    testImplementation("org.spockframework:spock-core:2.0-M4-groovy-2.5")
}
```

`SuperSpec.groovy`:
```
abstract class SuperSpec extends spock.lang.Specification {
    def "super feature"() {
        expect:
        false
    }
}
```

`SubSpec.groovy`:
```
class SubSpec extends SuperSpec {
    def "sub feature"() {
        expect:
        false
    }
}
```

Upon running the tests, `SubSpec.sub feature` gets retried as expected, while `SuperSpec.super feature` fails to be retried with:
```
org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
   SubSpec#super feature
```

Build scan with error: https://e.grdev.net/s/z5isufr33bfim

**Comment by rieske** [comment] 2021-01-25 09:04
This looks to be a known issue: https://github.com/gradle/test-retry-gradle-plugin/blob/fb1335dcd1db2e5d2d8dfbfee9b2478862aea796/plugin/src/test/groovy/org/gradle/testretry/testframework/Spock2FuncTest.groovy#L18-L24

Related to: https://github.com/spockframework/spock/issues/1235
which possibly points back to a problem in Gradle: https://github.com/gradle/gradle/issues/15185

**Comment by ldaley** [comment] 2021-01-26 23:21
@rieske it's quite certain that the problem is in Gradle and relevant details have been collected in the issue you linked to. I'm going to close this.

**Closed by ldaley** 2021-01-26 23:21 UTC
Labels: wontfix
