### ISSUE TITLE
Unable to retry Junit5 DynamicTests.

### ISSUE THREAD

**Issue by dacloutier-logmein** [gradle/test-retry-gradle-plugin#83] opened 2021-01-08 15:47 UTC
So, I have those test suites that will take a test and create dynamic versions of the tests as required by the environment configuration list that it is being passed on.

If a test fail, the retry plugin is unfortunately unable to rerun it:

Here's the stack trace I get:

```
➜ gradle clean test -DincludeTags='api | regression' -DexcludeTags='non' --stacktrace

> Task :test

ExampleBrowserBasedTest > executeTestContent - firefox - Local FAILED
    org.opentest4j.AssertionFailedError at ExampleBrowserBasedTest.java:84

[....] removed similar lines as ^^ to make stack smaller

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[5]
     com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[7]
     com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[6]
     com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[8]


* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:200)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:198)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalStateException: org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
   com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[5]
   com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[7]
   com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[6]
   com.jive.onboarding.e2e.ExampleBrowserBasedTest#exampleTestThatRunsInAllTags()[8]

        at org.gradle.testretry.internal.executer.RetryTestExecuter.failWithNonRetriedTestsIfAny(RetryTestExecuter.java:119)
        at org.gradle.testretry.internal.config.TestTaskConfigurer$FinalizeTaskAction.execute(TestTaskConfigurer.java:109)
        at org.gradle.testretry.internal.config.TestTaskConfigurer$FinalizeTaskAction.execute(TestTaskConfigurer.java:103)
        at org.gradle.testretry.internal.config.TestTaskConfigurer$ConditionalTaskAction.execute(TestTaskConfigurer.java:85)
        at org.gradle.testretry.internal.config.TestTaskConfigurer$ConditionalTaskAction.execute(TestTaskConfigurer.java:72)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:555)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:540)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:523)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:271)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:260)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:34)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:34)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:42)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 31s
5 actionable tasks: 4 executed, 1 up-to-date

```

Here's a stripped down version of the test class. (You should probably be able to make a simpler version that does an "assert" instead of trying to run an E2E test. 

```
@Slf4j
@Execution(CONCURRENT)
public class ExampleBrowserBasedTest extends BaseTest
{

  @Tags({ @Tag("suite") })
  @TestFactory
  public List<DynamicTest> exampleTestThatRunsOnlyOnSuiteTags()
  {
    return environmentConfigurations
        .stream()
        .parallel()
        .map(environmentConfiguration ->
            dynamicTest(
                String.format("executeTestContent - %s",
                    getTestConfiguration(environmentConfiguration)),
                () -> executeTestContent(environmentConfiguration)))
        .collect(Collectors.toList());
  }
  
  private void executeTestContent(@NonNull final HashMap<String, String> environmentConfiguration)
  {
    // Setup webdriver specific to the test run configuration
    final WebDriver driver = setWebDriver(environmentConfiguration);
    try
    {
      // This is the core of the test
      open(config
          .getAppBaseUrl()
          .get(executionEnvironment));
      ExamplePage.examplePageSteps(config
          .getIsolationEnvironments()
          .get(environmentConfiguration.get("isolationEnvironments"))
          .get("credentials"));
    }
    finally
    {
      // ensures the driver is shut down should the test fail mid-run.
      cleanUpWebdriver(driver);

      // also, this would be the place to complete your test specific cleanup.
    }
  }
}
```

Just to let you know, those are my first steps in using Gradle, as my previous projects were all using Maven.

**Comment by ldaley** [comment] 2021-01-11 00:07
The relevant part is here:

https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/main/java/org/gradle/testretry/internal/executer/framework/BaseJunitTestFrameworkStrategy.java#L63

For each of the failed iterations, we'll “select” it and it with the `[.+]` stripped from the end. This usually works…

https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/test/groovy/org/gradle/testretry/testframework/JUnit5FuncTest.groovy#L221

Something must be different about this `TestFactory` JUnit 5 construct. It could be that this is falling down at the Gradle test selection level.

@marcphilipp any ideas off the top of your head?

**Comment by marcphilipp** [comment] 2021-01-11 11:51
I did a quick experiment and Gradle can select the above test factory method as `ExampleBrowserBasedTest.exampleTestThatRunsOnlyOnSuiteTags`. Thus, I'm guessing we must not be stripping the `()[8]` suffixes here for some reason.

I tried to reproduce the issue with the following test class but it worked:
```java
@Execution(CONCURRENT)
class DynamicTests {

	@Tag("suite")
	@TestFactory
	List<DynamicTest> factory() {
		return List.of(dynamicTest("foo", () -> fail("boom")));
	}
}
```

Which versions of Gradle and JUnit are you using? Would it be possible for you to provide a build scan?

**Comment by ldaley** [comment] 2021-01-12 00:02
I also cannot reproduce.

@dacloutier-logmein are you also possible to provide a self contained example that has the problem?

**Comment by dacloutier-logmein** [comment] 2021-01-12 00:25
I will try to provide you with an example, I will put the kids to bed and get on it :)

**Comment by dacloutier-logmein** [comment] 2021-01-12 01:24
So, I just created a stripped down version of my tests, it work just fined. I then proceeded to revisit what I had done I took my active branch and not the one I used at the time and now it works.

What I suspect is there might have been some sort of incompatibility down the chain of dependency that could have caused Junit/Gradle-Retry to behave like this. 

That really sucks as since this is my first steps with gradle, I can't really figure what went wrong exactly.

At this point, I think we can close this issue.

For the record, I had this gradle.build file:

```
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id 'java'
    id 'maven-publish'
    id "io.freefair.lombok" version "5.3.0"
    id "org.gradle.test-retry" version "1.2.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri('https://PRIVATE_REPOSITORY/')
    }

    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {
    implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'com.codeborne:selenide:5.16.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.0'
    implementation 'com.browserstack:browserstack-local-java:1.0.6'
    implementation 'commons-io:commons-io:2.8.0'
    implementation 'com.google.oauth-client:google-oauth-client:1.31.2'
    implementation 'com.google.api-client:google-api-client-jackson2:1.20.0'
    implementation 'org.slf4j:slf4j-api:1.7.30'
    implementation 'io.opencensus:opencensus-contrib-http-util:0.28.2'
    runtimeOnly 'ch.qos.logback:logback-classic:1.2.3'
    runtimeOnly 'ch.qos.logback:logback-core:1.2.3'
    runtimeOnly 'org.slf4j:jcl-over-slf4j:1.7.30'
    runtimeOnly 'org.slf4j:jul-to-slf4j:1.7.30'
    runtimeOnly 'org.slf4j:log4j-over-slf4j:1.7.30'
    runtimeOnly 'ch.qos.logback:logback-classic:1.2.3'
    runtimeOnly 'ch.qos.logback:logback-core:1.2.3'
    runtimeOnly 'org.slf4j:jcl-over-slf4j:1.7.30'
    runtimeOnly 'org.slf4j:jul-to-slf4j:1.7.30'
    runtimeOnly 'org.slf4j:log4j-over-slf4j:1.7.30'
    testImplementation 'org.awaitility:awaitility:4.0.3'
    testImplementation 'org.mockito:mockito-core:3.5.7'
    testImplementation 'org.assertj:assertj-core:3.18.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testImplementation 'io.github.bonigarcia:selenium-jupiter:3.3.5'
    testImplementation 'org.awaitility:awaitility:4.0.3'
	testImplementation 'SOME_INTERNAL_DEPENDENCY#1'	
	testImplementation 'SOME_INTERNAL_DEPENDENCY#2'	
    testImplementation 'org.mockito:mockito-core:3.5.7'
    testImplementation('org.junit.jupiter:junit-jupiter-api:5.4.2')
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.6.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.1")

    compileOnly 'org.projectlombok:lombok:1.18.12'
    compileOnly 'org.projectlombok:lombok:1.18.16'
}

group = 'PROJECT_GROUP'
version = '0.0.0-development-SNAPSHOT'
description = 'PROJECT_DESCRIPTION'
java.sourceCompatibility = JavaVersion.VERSION_11

java {
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
 retry {
        maxRetries = 3
        maxFailures = 20
        failOnPassedAfterRetry = false
    }
    systemProperty "environment",System.getProperty("environment")
    String itags = System.getProperty("includeTags") ?
                   System.getProperty("includeTags") : 'suite';
    String etags = System.getProperty("excludeTags") ?
                   System.getProperty("excludeTags") : 'regression';
    useJUnitPlatform{
        includeTags  itags
        excludeTags  etags
    }
}
```

**Comment by ldaley** [comment] 2021-01-12 01:35
@dacloutier-logmein thanks for following up. If you see it again, please reopen this issue.

**Comment by dacloutier-logmein** [comment] 2021-01-12 01:51
> @dacloutier-logmein thanks for following up. If you see it again, please reopen this issue.

my pleasure, thanks for checking.

**Comment by dacloutier-logmein** [comment] 2021-01-12 13:44
hum I reproduced the issue again this morning. I think it has to do with the fact that tests are running in concurrent mode and that we need to have more than 1 simultaneous failure. 

The example basic test I tried last night was probably too fast trigger the issue.

**Comment by pshevche** [comment] 2024-04-24 14:40
@dacloutier-logmein , sorry that it took us a while to get to this issue. I took another look at it, and I can reproduce the issue using the following snippet:

```
@Execution(CONCURRENT)
class DynamicTests {

    @TestFactory
    List<DynamicTest> factory() throws IOException {
        Path marker = Paths.get("marker");
        boolean markerExists = Files.exists(marker);
        int iterationsCount = markerExists ? 5 : 10;
        if (!markerExists) {
            Files.createFile(marker);
        }

        return IntStream.range(0, iterationsCount)
            .parallel()
            .mapToObj(it -> dynamicTest("foo - " + it, () -> fail("boom")))
            .collect(Collectors.toList());
    }
}
```

Notice how the number of dynamic tests created is different between retries. In your case, it depends on `environmentConfigurations`. Are you sure that this object does not change between retries? This would explain the issues you are seeing. Other than that I don't see a reason why retries would fail for dynamic tests. I am going to close the issue, as I am afraid we won't be able to make much progress without a reproducer. Feel free to re-open if there is anything new from your side (... 3 years later 😅)

**Closed by pshevche** 2024-04-24 14:40 UTC
Labels: bug
