### ISSUE TITLE
Plugin is unable to retry unrolled methods

### ISSUE THREAD

**Issue by wolfs** [gradle/test-retry-gradle-plugin#48] opened 2020-05-12 09:01 UTC
It looks like the retry plugin is unable to retry this test: https://github.com/gradle/gradle/blob/fd75b0539be7421808fb2a45527c7e29cfd72fc4/subprojects/build-init/src/integTest/groovy/org/gradle/buildinit/plugins/KotlinLibraryInitIntegrationTest.groovy#L40-L61

or more particularly, `rg.gradle.buildinit.plugins.KotlinLibraryInitIntegrationTest#creates sample source if no source present with Kotlin build scripts`.

See https://e.grdev.net/s/ykkxlhpwrac6g for a build scan when the problem was reported.

**Comment by wolfs** [comment] 2020-05-12 09:02
Looks like the same issue here: https://e.grdev.net/s/eig4ki7c5azzw

**Comment by wolfs** [comment] 2020-05-12 09:04
And it seems like the problem was introduced by the retry plugin 1.1.5 :(

**Comment by ldaley** [comment] 2020-05-12 10:45
@wolfs very little has changed in this area since inception. Are you sure it's a regression?

**Comment by wolfs** [comment] 2020-05-12 11:16
@ldaley I looked at the failure dashboard for `*org.gradle.test-retry was unable to retry the following test methods, which is unexpected.*`, and the failures only started today, when we upgraded the plugin.

Ah, maybe it is related to us switching to using JUnit Platform for running the Spock tests instead of the old JUnit runner?

**Comment by blindpirate** [comment] 2020-05-12 11:28
@wolfs I know there's a known Spock-JUnit5Vintage-compatibility issue: https://github.com/gradle/gradle/issues/8787

I'm currently trying to create a reproducer and report this to retry-plugin issue tracker.

**Comment by blindpirate** [comment] 2020-05-12 14:58
Reproducer:

- Checkout https://github.com/gradle/gradle/compare/blindpirate/reproduce-retry-issue
- Run `./gradlew core:test --tests FlakyTest`

**Comment by ldaley** [comment] 2020-05-29 02:54
I've narrowed this down to Spock on JUnit 5. Still trying to sort it out.

**Comment by ldaley** [comment] 2020-05-29 06:47
Narrowed it down either to < 1.1.5 having a bug that meant that no retry was actually attempted in this case. That bug was fixed in 1.1.5, exposing that retrying on JUnit vintage has a ton of problems.

**Comment by ldaley** [comment] 2020-06-01 03:00
Superseded by #49

**Closed by ldaley** 2020-06-01 03:00 UTC
